name: Daily Commit

on:
  schedule:
    - cron: '00 13 * * *'  # This cron expression schedules the workflow to run at 1pm UTC every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make changes
        run: |
          echo "Automated commit on $(date)" >> dailySelf.txt

      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Automated commit on $(date)"
          git push https://$GITHUB_ACTOR:${{ secrets.GH_TOKEN }}@github.com/Zeeshan-Gulzar/self.git
