name: Daily Commit

on:
  schedule:
    - cron: '34 3 * * *'  # This cron expression schedules the workflow to run at midnight every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make changes
        run: |
          echo "Automated commit on $(date)" >> dailySelf.txt

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Automated commit on $(date)"
          git push
